#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# autostart
~/.fehbg

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod4   # Use the super key as the main modifier

# program launcher
hc keybind $Mod-d spawn rofi -show drun

# switch to another window 
hc keybind $Mod-w spawn rofi -show window

# lock screen
hc keybind $Mod-Shift-x spawn i3lock -fei ~/images/lockscreen.png

# this script changes colors for hlwm, dunst and rofi
hc keybind $Mod-b spawn wal --iterative -i ~/images -o ~/scripts/colors.sh

# music player daemon
hc keybind $Mod-F9 spawn mpc prev
hc keybind $Mod-F10 spawn mpc toggle
hc keybind $Mod-F11 spawn mpc next

# screenshots
hc keybind Print spawn ~/scripts/screenshot.sh screen
hc keybind Shift-Print spawn ~/scripts/screenshot.sh window
hc keybind Ctrl-Print spawn ~/scripts/screenshot.sh selection

# audio - speaker volume
hc keybind XF86AudioMute spawn pactl set-sink-mute @DEFAULT_SINK@ toggle
hc keybind XF86AudioLowerVolume spawn pactl set-sink-volume @DEFAULT_SINK@ -2%
hc keybind XF86AudioRaiseVolume spawn pactl set-sink-volume @DEFAULT_SINK@ +2%
hc keybind $Mod-F6 spawn pactl set-sink-mute @DEFAULT_SINK@ toggle
hc keybind $Mod-F7 spawn pactl set-sink-volume @DEFAULT_SINK@ -2%
hc keybind $Mod-F8 spawn pactl set-sink-volume @DEFAULT_SINK@ +2%

# audio - microphone
hc keybind $Mod-XF86AudioLowerVolume chain , spawn pactl set-source-volume @DEFAULT_SOURCE@ -2% , spawn polybar-msg action microphone hook 0
hc keybind $Mod-XF86AudioRaiseVolume chain , spawn pactl set-source-volume @DEFAULT_SOURCE@ +2% , spawn polybar-msg action microphone hook 0
hc keybind $Mod-Shift-F7 chain , spawn pactl set-source-volume @DEFAULT_SOURCE@ -2% , spawn polybar-msg action microphone hook 0
hc keybind $Mod-Shift-F8 chain , spawn pactl set-source-volume @DEFAULT_SOURCE@ +2% , spawn polybar-msg action microphone hook 0

# brightness
hc keybind XF86MonBrightnessDown spawn xbacklight -dec 10
hc keybind XF86MonBrightnessUp spawn xbacklight -inc 10
hc keybind $Mod-F2 spawn xbacklight -dec 10
hc keybind $Mod-F3 spawn xbacklight -inc 10

hc keybind $Mod-Shift-e quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-q close_or_remove
hc keybind $Mod-Return spawn "urxvt"

# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-i       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep

# tags
tag_names=( {1..10} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle

# colors are set by separate script (hlwm-theme.sh should be in script directory)
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_width 0
hc set always_show_frame on
hc set focus_follows_mouse true
hc set frame_bg_transparent off
hc set frame_transparent_width 0
hc set frame_gap 0

# this will remove title bar from windows
hc attr theme.title_height 0
hc attr theme.title_font 'Dejavu Sans:pixelsize=12'  # example using Xft
# hc attr theme.title_font '-*-fixed-medium-r-*-*-13-*-*-*-*-*-*-*'
hc attr theme.padding_top 0  # space below the title's baseline (i.e. text depth)
hc attr theme.inner_width 0
hc attr theme.border_width 3
hc attr theme.floating.border_width 3
hc attr theme.floating.outer_width 0

# copy inner color to outer_color
for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done

hc set window_gap 0
hc set frame_padding 0
hc set frame_active_opacity 50
hc set frame_normal_opacity 25
hc set smart_window_surroundings off
hc set smart_frame_surroundings off
hc set mouse_recenter_gap 0

# rules
hc unrule -F
hc rule switchtag=on
hc rule floatplacement=smart
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc rule class~'qutebrowser|firefox' tag=1 index=0
hc rule class~'mpv' tag=4
hc rule class~'qBittorrent' tag=10
hc rule class~'Pcmanfm' floating=on floatplacement=center
hc rule class~'Steam' floating=on tag=3

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock
~/scripts/colors.sh

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# panel=~/.config/herbstluftwm/panel.sh
# [ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
# for monitor in $(hc list_monitors | cut -d: -f1) ; do
#     # start it on each monitor
#     "$panel" "$monitor" &
# done
